chore: update publish.yaml for resource not accessible by integration
HttpError: Resource not accessible by integration. This error might be because of update which changesets bot received 3 weeks ago. Or maybe in our configuration of org repository.